#!/bin/sh
python createdb.py
python settleup/manage.py syncdb --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
python settleup/manage.py collectstatic --noinput
